# .pages.yml
media:
  # Lets you upload any assets used by posts
  - name: assets
    label: Assets
    input: src/assets
    output: /assets
    path: /assets
    categories: [image, document, audio, video]

content:
  - name: blog
    label: Blog posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: pubDate
        label: Published on
        type: date
        required: true
      - name: updatedDate
        label: Updated on
        type: date
        required: false
      - name: tags
        label: Tags
        type: list
        items:
          type: string
      - name: cover
        label: Cover image path (e.g. "@/assets/blogimages/my-post/cover.jpg")
        type: string
        description: 'Paste an "@/assets/..." path (see step 4).'
      - name: body
        label: Body
        type: rich-text
